config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/gallery', to: 'pages#gallery'
  get '/tours', to: 'pages#tours'
  get '/itinerary', to: 'pages#itinerary'
  get '/contact', to: 'pages#contact'
  get '/info', to: 'pages#info'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["HOST"] || "localhost:3000" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only:
  [:home, :gallery, :tours, :itinerary, :prices, :info, :contact]

  def home
  end

  def gallery
  end

  def tours
  end

  def itinerary
    # pin_markers
  end

  def prices
  end

  def info
  end

  def contact
  end

  private

  def pin_markers
    @markers = [
      {lng: 77.21, lat: 28.64},
      {lng: 74.87, lat: 31.63},
      {lng: 76.50, lat: 30.83},
      {lng: 78.26, lat: 30.08}
    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Bhavana Experiences - Cultivate your mind</title>
    <%= favicon_link_tag asset_path('favicon.ico'), rel: 'icon', type: "images/x-icon" %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/contact.html.erb
<div id="main-banner-contact" class="darken-overlay">
  <div class="darken-overlay">
    <%= render 'shared/navbar' %>
    <div class="main-banner-container">
      <div class="wrapper">
        <<h1><span>BHAVANA EXPERIENCES</span></h1>
      </div>
      <section id="section05" class="demo">
        <a href="#section06"><span></span>contact details</a>
      </section>
    </div>
  </div>
</div>
<section id="section06">
<div class="container contact-container">
    <div class="fa-icon">
    <h2>Contact me</h2><br>
    <div class="orange"><i class="fab fa-whatsapp"></i> +44 7858 951900</div>
    <div class="orange"><i class="fas fa-at"></i> bhavanaexperiences@gmail.com</div>
    <div class="orange"><i class="fab fa-instagram"></i> bhavanaexperiences</div><br><br>
    <div class="contact-page d-none d-md-block">
      <div class="home-body">
        <div class="card-product">
           <%= image_tag "ruby.jpg", class: "contact-img" %>
          <div class="card-product-infos">
            <i class="fas fa-quote-left orange "></i>
              <p class="orange"><small>I have been travelling independently since 2010 and through doing so I've grown emotionally, intellectually and, more recently, spiritually. <br>Despite being 9 years into this journey, I often feel like I'm just at the beginning. <br>No matter how much I travel I am always delighted and often speechless when I encounter something new. <br>One of the things that I love most about India is that I am continuously experiencing something new. No two days here are the same.</small></p>
              <p>
                I am not ready to finish my journey and would love to share it with you, whoever you may be.
              </p>
              <i class="fas fa-quote-right orange"></i>
          </div>
        </div>
      </div>
    </div>
    <div class="d-md-none">
        <div class="small-container">
          <%= image_tag "ruby.jpg", class: "contact-img" %><br><br>
          <i class="fas fa-quote-left orange "></i>
          <p class="orange"><small>I have been travelling independently since 2010 and through doing so I've grown emotionally, intellectually and, more recently, spiritually. <br>Despite being 9 years into this journey, I often feel like I'm just at the beginning. <br>No matter how much I travel I am always delighted and often speechless when I encounter something new. <br>One of the things that I love most about India is that I am continuously experiencing something new. No two days here are the same.</small></p>
          <p>
            I am not ready to finish my journey and would love to share it with you, whoever you may be.
          </p>
          <i class="fas fa-quote-right orange"></i>
        </div>
    </div>
  </div>
</section>

app/views/pages/gallery.html.erb
<div id="main-banner-gallery" class="darken-overlay">
    <div class="darken-overlay">
        <%= render 'shared/navbar' %>
        <div class="main-banner-container">
          <div class="wrapper">
            <h1><span>BHAVANA EXPERIENCES</span></h1>
          </div>
          <section id="section05" class="demo">
            <a href="#section06"><span></span>view pictures</a>
          </section>
          </div>
    </div>
</div>
<section id="section06">
  <div class="content-container">
    <div class="inner-content">
      <div class="text-box">
        <i class="fas fa-camera-retro orange icon"></i>
        <h2 class="orange">Gallery</h2>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="post-module">
        <div class="thumbnail" id="myImg">

          <%= image_tag ( "taj_nopeople.jpg") %>
        </div>
        <div class="post-content" >
          <p class="title">Taj Mahal</p>
          <p class="description">Description</p>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="post-module">
        <div class="thumbnail" id="myImg2">
          <%= image_tag ( "ceremonynight.jpg") %>
        </div>
        <div class="post-content">
          <p class="title">Wagah Border Ceremony</p>
          <p class="description">Description</p>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="post-module">
        <div class="thumbnail" >
          <%= image_tag ( "earcleaner.jpg") %>
        </div>
        <div class="post-content">
          <p class="title">Get your ears cleaned</p>
          <p class="description">Description</p>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="post-module">
        <div class="thumbnail" >
          <%= image_tag ( "bathinginriver.jpg") %>
        </div>
        <div class="post-content">
          <p class="title">Bath in the Ganges</p>
          <p class="description">Description</p>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="post-module">
        <div class="thumbnail" >
          <%= image_tag ( "park.jpg") %>
        </div>
        <div class="post-content">
          <p class="title">Chillout in the park</p>
          <p class="description">Description</p>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="post-module">
        <div class="thumbnail" >
          <%= image_tag ( "delhi.jpg") %>
        </div>
        <div class="post-content">
          <p class="title">Visit Delhi</p>
          <p class="description">Description</p>
        </div>
      </div>
    </div>
   <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="post-module">
        <div class="thumbnail" >
          <%= image_tag ( "river2.jpg") %>
        </div>
        <div class="post-content">
          <p class="title">Ceremonies on the Ganges</p>
          <p class="description">Description</p>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="post-module">
        <div class="thumbnail" >
          <%= image_tag ( "olddelhi.jpg") %>
        </div>
        <div class="post-content">
          <p class="title">Visit Old Delhi</p>
          <p class="description">Description</p>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="post-module">
        <div class="thumbnail" >
          <%= image_tag ( "weloverish.jpg") %>
        </div>
        <div class="post-content">
          <p class="title">Visit Rishakesh</p>
          <p class="description">Description</p>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- currently, this works adding the id too the taj mahal photo -->
<!-- uncomment line 131 onwards to make it work -->
<!-- The Modal -->
<!-- <div id="myModal" class="modal"> -->

  <!-- The Close Button -->
  <!-- <span class="close">&times;</span> -->

  <!-- Modal Content (The Image) -->
  <!-- <div class="modal-content"> -->
   <!-- <%#= image_tag ( "taj_nopeople.jpg") %> -->
  <!-- </div> -->

  <!-- Modal Caption (Image Text) -->
  <!-- <div id="caption">Insert description</div> -->
<!-- </div> -->

</section>

app/views/pages/home.html.erb
<div id="main-banner-home" class="darken-overlay">
  <div class="darken-overlay">
    <%= render 'shared/navbar' %>
    <div class="main-banner-container">
      <div class="wrapper">
        <h1><span>BHAVANA EXPERIENCES</span></h1>
      </div>
      <section id="section05" class="demo">
        <a href="#section06"><span></span>learn more</a>
      </section>
    </div>
  </div>
</div>
<section id="section06">
  <div class="container">
    <div class="info-container">
      <h2><strong>What I Offer</strong></h2>
      <p><small>I organise budget tours to India. Experience the 'Real India' accompanied by one British and one Indian tour guide. I am here to encourage you to step out of your comfort zone without compromising your comfort.</small></p>
      <div class="row">
        <div class="col-xs-12 col-md-4">
          <div class="info-card orange">
            <h1><i class="fas fa-plane-arrival"></i></h1>
            <p><small>Picked up at the airport</small></p>
          </div>
        </div>
        <div class="col-xs-12 col-md-4">
          <div class="info-card orange">
            <h1><i class="fas fa-globe-africa"></i></h1>
            <p><small>Taken on an adventure</small></p>
          </div>
        </div>
        <div class="col-xs-12 col-md-4">
          <div class="info-card orange">
            <h1><i class="fas fa-plane-departure"></i></h1>
            <p><small>Dropped off at the airport</small></p>
          </div>
        </div>
      </div>
      <div><br></div>
      <div class="row">
          <div id="bhavana" class="d-md-none">
            <p><strong>Bhavana</strong> in the ancient Sanskrit language means to cultivate</p>
          </div>
        <div class="home-body">
          <div class="i-container">
            <div class="card-product">
              <!-- following image stored in public folder -->
              <img src="goldentemplenight.jpg" alt="Avatar" class="image">
              <div class="middle">
                <!-- uncomment next line to add text to center of middle container -->
                <!-- <div class="text">John Doe</div> -->
                <h1><i class="orange fas fa-route" style="font-size: 6vw"></i></h1>
              </div>
            <div class="card-product-infos">
              <h1 class="orange"><strong>What</strong></h1>
              <div class="d-none d-md-block">
                <p><strong>Bhavana</strong> in the ancient Sanskrit language means to cultivate.<br> I aim to create tours in which you feel <strong>safe</strong> and <strong>comfortable</strong>, so that you can absorb the magic of India.<br> I hope that through experiencing India with me, it will broaden your horizons and cultivate your mind.</p>
            </div>
              <div class="d-md-none">
                <p>Comfortable and <strong>safe</strong> tours around India</p>
              </div>
              </div>
            </div>
          </div>
          <div class="i-container">
            <div class="card-product">
              <div class="card-product-infos">
                <h1 class="orange"><strong>Why</strong></h1>
                <div class="d-none d-md-block">
                  <p>Over the years, many people have been shocked by my <strong>confidence</strong> and even look up to me in awe. Some of the comments I often hear are: <br><br> "How do you do it?!" <br> "You're so <strong>brave</strong>!" <br> "I could never do what you do." <br><br> I want you to hear the same when you get home.</p>
                </div>
                <div class="d-md-none">
                  <p>Gain <strong>confidence</strong> and realise how <strong>brave</strong> you really are</p>
                </div>
              </div>
              <!-- following image stored in public folder -->
              <img src="taj_people.jpg" alt="Avatar" class="image">
              <div id="second">
                <div class="middle">
                  <!-- uncomment next line to add text to center of middle container -->
                  <!-- <div class="text">Doe</div> -->
                  <h1><i class="orange fas fa-users" style="font-size: 6vw"></i></h1>
                </div>
              </div>

            </div>
          </div>
          <div class="i-container">
            <div class="card-product">
              <!-- following image stored in public folder -->
              <img src="goldentemple.jpg" alt="Avatar" class="image">
              <div class="middle">
                <!-- uncomment next line to add text to center of middle container -->
                <!-- <div class="text">John Doe</div> -->
                <h1><i class="orange fas fa-rupee-sign" style="font-size: 6vw"></i></h1>
              </div>
              <div class="card-product-infos">
                <h1 class="orange"><strong>How</strong></h1>
                <div class="d-none d-md-block">
                  <p>It's really important to me that I plan a trip that I would also enjoy. <br>So I am not planning tour bus holidays where we will be jumping on and off a bus. <br>We'll be trying to experience <strong>"the real India"</strong> as much as possible - that's why we will be traveling between our destinations by train.</p>
                </div>
                <div class="d-md-none">
                  <p>By experiencing the <strong>real </strong>India</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/info.html.erb
<div id="main-banner-info" class="darken-overlay">
  <div class="darken-overlay">
    <%= render 'shared/navbar' %>
    <div class="main-banner-container">
      <div class="wrapper">
        <h1><span>BHAVANA EXPERIENCES</span></h1>
      </div>
      <section id="section05" class="demo">
        <a href="#section06"><span></span>Important information</a>
      </section>
    </div>
  </div>
</div>
<section id="section06">
  <div class="container">
    <div class="content-container">
      <div class="inner-content">
        <div class="text-box">
          <i class="fas fa-syringe orange icon"></i>
          <h2 class="orange">Jabs</h2>
          <p><small>According to the NHS <a href="https://www.fitfortravel.nhs.uk/destinations/asia-east/india" class="orange">fit for travel</a> website, there are a some vaccinations you need to travel to India*. </small></p>
          <ul class="list-unstyled">
            <li><p><small>all primary courses and boosters for immunisations needed for living in Britain (e.g. MMR)</small></p></li>
            <li><p><small>advised vaccinations: Diphtheria; Hepatitis A; Tetanus; Typhoid</small></p></li>
            <li><p><small>addition vaccinations to consider: Hepatitis A & rabies</small></p></li>
          </ul class="list-unstyled">
          <p><small>I have had all of the above except rabies which I have not had.</small></p>
          <p><small>According to the NHS <a href="https://www.fitfortravel.nhs.uk/destinations/asia-east/india/india-malaria-map" class="orange">fit for travel</a> website, you do not need to take anti-malaria medication in the regions in India covered in my tours.</small></p>
          <p><small><strong>*I am not a medical professional and an appointment with a travel nurse should be arranged at least 6 weeks before travel.</strong></small></p>
        </div>
        <div class="text-box">
          <i class="fas fa-user-md orange icon"></i>
          <h2 class="orange">Staying Healthy</h2>
          <ul class="list-unstyled">
            <li><p><small>When travelling to India you may want to consider purchasing probiotic tablets from a health foods shop. Probiotics help maintain 'friendly' bacteria in the digestive tract which can be useful in fighting against 'unfriendly' bacteria - the bacteria which can cause the dreaded Delhi belly, yeast infections or diarrhea.</small></p></li>
            <li><p><small>Drinking tap water India is not safe. Bottled drinking water is readily available for 20Rupees (approx. 22p) and many restaurant provide purified, filtered drinking water. </small></p></li>
            <li><p><small>Drinking tap water India is not safe. Bottled drinking water is readily available for 20Rupees (approx. 22p) and many restaurant provide purified, filtered drinking water. </small></p></li>
            <li><p><small>It is also recommended to use bottled water for brushing your teeth with. </small></p></li>
            <li><p><small>For a short trip to India its also best to avoid salad which has been rinsed and has water on it and ice cubes. Personally I eat salad and ice cubes but I have been here for a long time so my stomach has adapted.</small></p></li>
            <li><p><small>It's best to chose fruit which have skins which are easy to remove and non-edible - such as bananas, oranges, pineapples etc.</small></p></li>
            <li><p><small>Packing re-hyrdation sachets is highly recommended, they're great for replenishing fluids and electrolytes if you do feel slightly under the weather.</small></p></li>
          </ul>
        </div>
        <div class="text-box">
          <i class="fas fa-globe orange icon"></i>
          <h2 class="orange">Visa Info</h2>
          <ul class="list-unstyled">
            <li><p><small>A visa is required for foreign visitors to India. Tourists from the UK can apply for an e-visa which costs $100 (approx. £78). You can apply for an e-visa online during the window of 120 - 4 days in advance of arrival in India.</small></p></li>
            <li><p><small>Foreign visitors to India are required to have 6 months validity in their passport, 2 blank pages and your passport must be machine readable.</small></p></li>
            <li><p><small>More information regarding Indian e-visas can be found at <a href="https://indianvisaonline.gov.in/visa/index.html" class="orange">indianvisaonline.gov</a>. I'll send a reminder to apply for your visa closer to the time of travel.</small></p></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/itinerary.html.erb
<div id="main-banner-itinerary" class="darken-overlay">
  <div class="darken-overlay">
    <%= render 'shared/navbar' %>
    <div class="main-banner-container">
      <div class="wrapper">
        <<h1><span>BHAVANA EXPERIENCES</span></h1>
      </div>
      <section id="section05" class="demo">
        <a href="#section06"><span></span>itinerary</a>
      </section>
    </div>
  </div>
</div>
<section id="section06">
  <div class="container">
    <div class="content-container">
          <i class="fas fa-train orange icon" style="margin: 10px 0"></i><br>
          <h3 class="orange">India</h3><br>
          <h5 class="orange">10 day trip to North India, uniting like-minded people over their desire to travel and experience a new country and culture.</h5><br>
          <p><small>
            Everything that you see on the itinerary is based on my own experiences, we'll be doing things which I have already done and loved. As previously mentioned, we will be travelling by train. The class that we'll travel by is actually very similar to English trains but you'll notice how much more open the people are. Indians are very curious about foreign visitors and are eager to start friendly conversations.
          </small>
          </p>
          <br>

          <p class="orange"><strong>Upcoming Dates</strong></p>
          <p><small>15th September - 25th September 2019</small></p>
          <br>
          <p class="orange"><strong>Price</strong></p>
          <p><small><strong>Single Occupancy : </strong>  64,800 Rupees (Approx. £720) </small></p>
          <p><small><strong> Double Occupancy : </strong>  54,000 Rupees per person (Approx. £600pp)</small></p><br>

          <div class="row">
            <div class="col-xs-6 col-md-4">
              <div class="info-card orange">
                <h1><i class="fas fa-map-marker-alt orange"></i></h1>
                <p><small>Starting Point</small></p>
                <p><strong>Delhi</strong></p>
              </div>
            </div>
            <div class="col-xs-6 col-md-4">
              <div class="info-card text-center orange">
                <h1><i class="far fa-clock"></i></h1>
                <p><small>Duration</small></p>
                <p><strong>10 days</strong></p>
              </div>
            </div>
            <div class="col-xs-6 col-md-4">
              <div class="info-card text-center orange">
                <h1><i class="fas fa-users"></i></h1>
                <p><small>Number of Participants</small></p>
                <p><strong>4 to 8</strong></p>
              </div>
            </div>
            <div class="col-xs-6 col-md-6">
              <div class="info-card orange">
                <h1><i class="fas fa-campground"></i></h1>
                <p><small>Accomodation</small></p>
                <p><strong>Hotel(s)</strong></p>
              </div>
            </div>
            <div class="col-xs-12 col-md-6">
              <div class="info-card orange">
                <h1><i class="fas fa-train"></i></h1>
                <p><small>Transport</small></p>
                <p><strong>Train</strong></p>
              </div>
            </div>
          </div>

          <!-- <div class="text-box"> -->
            <p class="orange"><strong>Highlights</strong></p>
            <p><small>Enjoy delicious traditional food, sip hot chai, dip your toes in the River Ganges and try yoga in the world capital of yoga, marvel at world famous landmarks; The Golden Temple and The Taj Mahal, make new friends on the Indian railways, experience Punjabi village life, witness the India-Pakistan border closing ceremony, and much much more. <br>Please click on the markers below for the itinerary (only available on desktop, if you are a mobile user please click here)</small></p>
          <div class="map-container d-none d-md-block">
            <div id="map"></div>
          </div>
          <div class="image d-md-none">
            <%= image_tag "map"%>
          </div>
          <p class="orange"><strong>Additional Costs</strong></p>
          <p><small>A visa is required to enter India. You'll need an e-visa which costs $100 (£78 approx).
          <br>Return flights are currently around £400 but are likely to increase so early booking is recommended. You are responsible for booking your own flight.
          <br>Travel insurance is required which can be obtained cheaply from <a href="https://www.comparethemarket.com/travel-insurance/" class="orange">comparison websites</a></small></p>
          <p class="orange"><strong>Please Note</strong></p>
          <p><small>Please note that price in British Pounds may vary depending on the exchange rate at the time of payment. The price in Rupees is fixed, pound values are only approximate.
          <br> A £50pp deposit is required to secure a place. Full balance will be due 4 weeks before departure.</small></p><br>
          <p><small><strong><%= link_to " Click here for Travel and Visa information", info_path, class: "link" %></strong></small></p>
    </div>
  </div>
  <%= javascript_include_tag "https://maps.google.com/maps/api/js?key=#{ENV['GOOGLE_MAPS_API_KEY']}" %>
</section>
  <!--         <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="info-card orange">
              <h1><i class="fas fa-rupee-sign"></i></h1>
              <p><small>Price</small></p>
            </div>
          </div> -->

app/views/pages/tours.html.erb
<script type="text/javascript" src="js/mdb.js"></script>
<div id="main-banner-tours" class="darken-overlay">
    <div class="darken-overlay">
      <%= render 'shared/navbar' %>
      <div class="main-banner-container">
        <div class="wrapper">
          <h1><span>BHAVANA EXPERIENCES</span></h1>
         </div>
         <section id="section05" class="demo">
            <a href="#section06"><span></span>view tours</a>
          </section>
      </div>
    </div>
</div>
<section id="section06">
<div class="font-awsome-responsive">
  <div class="content-container">
    <div class="inner-content">
      <div class="text-box">
       <i class="fas fa-map-marked-alt orange icon"></i>
        <h2 class="orange">Tours</h2>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="d-none d-md-block">
    <div class="home-body">
      <div class="card-product" id="tours">
         <%= image_tag "street.jpg" %>
        <div class="card-product-infos">
          <div class='product-body'>
            <h3><strong>Experience India With Ruby</strong></h3>
              <p>I want to show you that you can. By organising group trips to India I hope that you can step out of your comfort zone without compromising your comfort. I aim to create tours in which you feel safe so that you can relax and absorb the magic of India. To allow you to do so, I will be with you every step of the way.</p>
            <br>
            <br>
            <%= link_to "find out more", itinerary_path, class: "link" %>
            </div>
          </div>
        </div>
    </div>
  </div>
  <div class="d-md-none">
    <div class="home-body" id="small-device-only">
      <%= image_tag "street.jpg" %><br>
        <h3><strong>Experience India With Ruby</strong></h3><br><br>
          <p>I want to show you that you can. By organising group trips to India I hope that you can step out of your comfort zone without compromising your comfort. I aim to create tours in which you feel safe so that you can relax and absorb the magic of India. To allow you to do so, I will be with you every step of the way.</p>
          <%= link_to "find out more", itinerary_path, class: "link" %>
    </div>
  </div>
    <h4 class="text-center" style="margin: 50px">More tours coming soon...</h4>
</div>
</section>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/bhavanaexperiences/"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/Bhavanaexperiences/" target="_blank"><i class="fab fa-facebook"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<script src = "https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
  $(document).ready(function () {
    $('.first-button').on('click', function () {
      $('.animated-icon1').toggleClass('open')
    });
  });
</script>
<div class="navbar navbar-expand-md navbar-light">
  <div class="float-right">
    <div class="home">
      <a class="navbar-wagon-item">
        <%= link_to "Home", root_path, class: "home nav-link" %>
      </a>
    </div>
  </div>

    <button class="navbar-toggler first-button" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <div class="animated-icon1"><span></span><span></span><span></span></div>
    </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="float-right">
      <div class="center">
        <ul class="navbar-nav mr-auto">
          <%# if user_signed_in? %>
    <!--    <li class="nav-item active">
              <%#= link_to "Home", "#", class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%#= link_to "Messages", "#", class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <%#= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%#= link_to "Action", "#", class: "dropdown-item" %>
                <%#= link_to "Another action", "#", class: "dropdown-item" %>
                <%#= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li> -->
          <%# else %>

          <li class="navbar-wagon-item">
            <%= link_to "Gallery", gallery_path, class: "nav-link" %>
          </li>
          <li class="navbar-wagon-item">
            <%= link_to "Tours", tours_path, class: "nav-link" %>
          </li>
          <li class="navbar-wagon-item">
            <%= link_to "Contact", contact_path, class: "nav-link" %>
          </li>
          <%# end %>
        </ul>
      </div>
    </div>
  </div>
</div>